"use client";

import React from "react";
import { FileText, KeyRound, Sparkles, Scale } from "lucide-react";

export const TermsConditionsScreen: React.FC = () => {
  return (
    <div className="flex flex-col items-center px-4 pt-1 pb-8 text-center w-full max-w-md mx-auto select-none">


      {/* Intro Overview Card */}
      <div
        className="w-full rounded-2xl p-4 mb-3 text-left relative overflow-hidden shadow-xl"
        style={{
          background: "rgba(255, 255, 255, 0.04)",
          border: "1px solid rgba(180, 120, 255, 0.22)",
        }}
      >
        <div className="flex items-start gap-3">
          <div
            className="w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 mt-0.5"
            style={{
              background: "rgba(124, 58, 237, 0.3)",
              border: "1px solid rgba(201, 108, 204, 0.4)",
            }}
          >
            <FileText size={16} className="text-[#f5d76e]" />
          </div>
          <p className="text-xs leading-relaxed text-purple-100/90">
            Welcome to <strong className="text-[#f5d76e]">Celys Care</strong>. By downloading, installing, or using our platform, you agree to the following terms.
          </p>
        </div>
      </div>

      {/* Section 1 */}
      <div
        className="w-full rounded-2xl p-4 mb-3 text-left shadow-md transition-all hover:bg-white/[0.05]"
        style={{
          background: "rgba(255, 255, 255, 0.03)",
          border: "1px solid rgba(180, 120, 255, 0.18)",
        }}
      >
        <div className="flex items-center gap-2.5 mb-2">
          <KeyRound size={15} className="text-[#c96ccc]" />
          <h2 className="text-xs sm:text-sm font-semibold text-[#f5d76e] tracking-wide">
            1. Usage License
          </h2>
        </div>
        <p className="text-xs leading-relaxed text-purple-200/80">
          We grant you a personal, non-exclusive, non-transferable license to use <strong className="text-white">Celys Care</strong> for personal or educational purposes.
        </p>
      </div>

      {/* Section 2 */}
      <div
        className="w-full rounded-2xl p-4 mb-3 text-left shadow-md transition-all hover:bg-white/[0.05]"
        style={{
          background: "rgba(255, 255, 255, 0.03)",
          border: "1px solid rgba(180, 120, 255, 0.18)",
        }}
      >
        <div className="flex items-center gap-2.5 mb-2">
          <Sparkles size={15} className="text-[#7ec8a0]" />
          <h2 className="text-xs sm:text-sm font-semibold text-[#f5d76e] tracking-wide">
            2. Intellectual Property
          </h2>
        </div>
        <p className="text-xs leading-relaxed text-purple-200/80">
          All content and materials generated by or licensed to <strong className="text-white">Celys Care</strong> are protected by copyright and other intellectual property laws.
        </p>
      </div>

      {/* Section 3 */}
      <div
        className="w-full rounded-2xl p-4 mb-4 text-left shadow-md transition-all hover:bg-white/[0.05]"
        style={{
          background: "rgba(255, 255, 255, 0.03)",
          border: "1px solid rgba(180, 120, 255, 0.18)",
        }}
      >
        <div className="flex items-center gap-2.5 mb-2">
          <Scale size={15} className="text-[#f87171]" />
          <h2 className="text-xs sm:text-sm font-semibold text-[#f5d76e] tracking-wide">
            3. Limitation of Liability
          </h2>
        </div>
        <p className="text-xs leading-relaxed text-purple-200/80">
          To the maximum extent permitted by law, <strong className="text-white">Celys Care</strong> will not be liable for any indirect, incidental, or consequential damages.
        </p>
      </div>

      {/* Footer Note */}
      <p
        className="text-[10px] text-center text-purple-200/40"
      >
        © 2026 Celys Care · All rights reserved · Your safe space. Your support. Your journey. 💜
      </p>
    </div>
  );
};

export default TermsConditionsScreen;
